// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: services/agents/teams.proto

package agents

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TeamType int32

const (
	TeamType_NETWORK     TeamType = 0
	TeamType_DEVELOPMENT TeamType = 1
	TeamType_HARDWARE    TeamType = 2
	TeamType_SOFTWARE    TeamType = 3
	TeamType_ERP         TeamType = 4
	TeamType_DATABASES   TeamType = 5
)

// Enum value maps for TeamType.
var (
	TeamType_name = map[int32]string{
		0: "NETWORK",
		1: "DEVELOPMENT",
		2: "HARDWARE",
		3: "SOFTWARE",
		4: "ERP",
		5: "DATABASES",
	}
	TeamType_value = map[string]int32{
		"NETWORK":     0,
		"DEVELOPMENT": 1,
		"HARDWARE":    2,
		"SOFTWARE":    3,
		"ERP":         4,
		"DATABASES":   5,
	}
)

func (x TeamType) Enum() *TeamType {
	p := new(TeamType)
	*p = x
	return p
}

func (x TeamType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TeamType) Descriptor() protoreflect.EnumDescriptor {
	return file_services_agents_teams_proto_enumTypes[0].Descriptor()
}

func (TeamType) Type() protoreflect.EnumType {
	return &file_services_agents_teams_proto_enumTypes[0]
}

func (x TeamType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TeamType.Descriptor instead.
func (TeamType) EnumDescriptor() ([]byte, []int) {
	return file_services_agents_teams_proto_rawDescGZIP(), []int{0}
}

type Team struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TeamType   TeamType `protobuf:"varint,2,opt,name=team_type,json=teamType,proto3,enum=TeamType" json:"team_type,omitempty"`
	AgentsList []*Agent `protobuf:"bytes,3,rep,name=agents_list,json=agentsList,proto3" json:"agents_list,omitempty"`
}

func (x *Team) Reset() {
	*x = Team{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_agents_teams_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Team) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Team) ProtoMessage() {}

func (x *Team) ProtoReflect() protoreflect.Message {
	mi := &file_services_agents_teams_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Team.ProtoReflect.Descriptor instead.
func (*Team) Descriptor() ([]byte, []int) {
	return file_services_agents_teams_proto_rawDescGZIP(), []int{0}
}

func (x *Team) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Team) GetTeamType() TeamType {
	if x != nil {
		return x.TeamType
	}
	return TeamType_NETWORK
}

func (x *Team) GetAgentsList() []*Agent {
	if x != nil {
		return x.AgentsList
	}
	return nil
}

var File_services_agents_teams_proto protoreflect.FileDescriptor

var file_services_agents_teams_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74,
	0x73, 0x2f, 0x74, 0x65, 0x61, 0x6d, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x2f, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x67, 0x0a, 0x04, 0x54,
	0x65, 0x61, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x09, 0x74, 0x65, 0x61, 0x6d, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x09, 0x2e, 0x54, 0x65, 0x61, 0x6d, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x08, 0x74, 0x65, 0x61, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x27, 0x0a, 0x0b, 0x61,
	0x67, 0x65, 0x6e, 0x74, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x06, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73,
	0x4c, 0x69, 0x73, 0x74, 0x2a, 0x5c, 0x0a, 0x08, 0x54, 0x65, 0x61, 0x6d, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x0b, 0x0a, 0x07, 0x4e, 0x45, 0x54, 0x57, 0x4f, 0x52, 0x4b, 0x10, 0x00, 0x12, 0x0f, 0x0a,
	0x0b, 0x44, 0x45, 0x56, 0x45, 0x4c, 0x4f, 0x50, 0x4d, 0x45, 0x4e, 0x54, 0x10, 0x01, 0x12, 0x0c,
	0x0a, 0x08, 0x48, 0x41, 0x52, 0x44, 0x57, 0x41, 0x52, 0x45, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08,
	0x53, 0x4f, 0x46, 0x54, 0x57, 0x41, 0x52, 0x45, 0x10, 0x03, 0x12, 0x07, 0x0a, 0x03, 0x45, 0x52,
	0x50, 0x10, 0x04, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x41, 0x54, 0x41, 0x42, 0x41, 0x53, 0x45, 0x53,
	0x10, 0x05, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x64, 0x7a, 0x77, 0x69, 0x65, 0x64, 0x7a, 0x39, 0x30, 0x2f, 0x68, 0x65, 0x6c, 0x70, 0x64,
	0x65, 0x73, 0x6b, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_services_agents_teams_proto_rawDescOnce sync.Once
	file_services_agents_teams_proto_rawDescData = file_services_agents_teams_proto_rawDesc
)

func file_services_agents_teams_proto_rawDescGZIP() []byte {
	file_services_agents_teams_proto_rawDescOnce.Do(func() {
		file_services_agents_teams_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_agents_teams_proto_rawDescData)
	})
	return file_services_agents_teams_proto_rawDescData
}

var file_services_agents_teams_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_services_agents_teams_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_services_agents_teams_proto_goTypes = []interface{}{
	(TeamType)(0), // 0: TeamType
	(*Team)(nil),  // 1: Team
	(*Agent)(nil), // 2: Agent
}
var file_services_agents_teams_proto_depIdxs = []int32{
	0, // 0: Team.team_type:type_name -> TeamType
	2, // 1: Team.agents_list:type_name -> Agent
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_services_agents_teams_proto_init() }
func file_services_agents_teams_proto_init() {
	if File_services_agents_teams_proto != nil {
		return
	}
	file_services_agents_agents_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_services_agents_teams_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Team); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_agents_teams_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_agents_teams_proto_goTypes,
		DependencyIndexes: file_services_agents_teams_proto_depIdxs,
		EnumInfos:         file_services_agents_teams_proto_enumTypes,
		MessageInfos:      file_services_agents_teams_proto_msgTypes,
	}.Build()
	File_services_agents_teams_proto = out.File
	file_services_agents_teams_proto_rawDesc = nil
	file_services_agents_teams_proto_goTypes = nil
	file_services_agents_teams_proto_depIdxs = nil
}
