// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.12.4
// source: services/users/departaments.proto

package users

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DepartamentType int32

const (
	DepartamentType_HUMAN_RESOURCES     DepartamentType = 0
	DepartamentType_FINANCES            DepartamentType = 1
	DepartamentType_SALES_AND_MARKETING DepartamentType = 2
	DepartamentType_CUSTOMER_SERVICE    DepartamentType = 3
	DepartamentType_LEGAL               DepartamentType = 4
	DepartamentType_PRODUCTION          DepartamentType = 5
	DepartamentType_QUALITY_ASSURANCE   DepartamentType = 6
)

// Enum value maps for DepartamentType.
var (
	DepartamentType_name = map[int32]string{
		0: "HUMAN_RESOURCES",
		1: "FINANCES",
		2: "SALES_AND_MARKETING",
		3: "CUSTOMER_SERVICE",
		4: "LEGAL",
		5: "PRODUCTION",
		6: "QUALITY_ASSURANCE",
	}
	DepartamentType_value = map[string]int32{
		"HUMAN_RESOURCES":     0,
		"FINANCES":            1,
		"SALES_AND_MARKETING": 2,
		"CUSTOMER_SERVICE":    3,
		"LEGAL":               4,
		"PRODUCTION":          5,
		"QUALITY_ASSURANCE":   6,
	}
)

func (x DepartamentType) Enum() *DepartamentType {
	p := new(DepartamentType)
	*p = x
	return p
}

func (x DepartamentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DepartamentType) Descriptor() protoreflect.EnumDescriptor {
	return file_services_users_departaments_proto_enumTypes[0].Descriptor()
}

func (DepartamentType) Type() protoreflect.EnumType {
	return &file_services_users_departaments_proto_enumTypes[0]
}

func (x DepartamentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DepartamentType.Descriptor instead.
func (DepartamentType) EnumDescriptor() ([]byte, []int) {
	return file_services_users_departaments_proto_rawDescGZIP(), []int{0}
}

type Departament struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              int64           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	DepartamentType DepartamentType `protobuf:"varint,2,opt,name=departament_type,json=departamentType,proto3,enum=DepartamentType" json:"departament_type,omitempty"`
	Users           []*User         `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
}

func (x *Departament) Reset() {
	*x = Departament{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_users_departaments_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Departament) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Departament) ProtoMessage() {}

func (x *Departament) ProtoReflect() protoreflect.Message {
	mi := &file_services_users_departaments_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Departament.ProtoReflect.Descriptor instead.
func (*Departament) Descriptor() ([]byte, []int) {
	return file_services_users_departaments_proto_rawDescGZIP(), []int{0}
}

func (x *Departament) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Departament) GetDepartamentType() DepartamentType {
	if x != nil {
		return x.DepartamentType
	}
	return DepartamentType_HUMAN_RESOURCES
}

func (x *Departament) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

var File_services_users_departaments_proto protoreflect.FileDescriptor

var file_services_users_departaments_proto_rawDesc = []byte{
	0x0a, 0x21, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73,
	0x2f, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x1a, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x75, 0x73,
	0x65, 0x72, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x77, 0x0a, 0x0b, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x3b,
	0x0a, 0x10, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x44, 0x65, 0x70, 0x61, 0x72,
	0x74, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0f, 0x64, 0x65, 0x70, 0x61,
	0x72, 0x74, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1b, 0x0a, 0x05, 0x75,
	0x73, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x05, 0x2e, 0x55, 0x73, 0x65,
	0x72, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x2a, 0x95, 0x01, 0x0a, 0x0f, 0x44, 0x65, 0x70,
	0x61, 0x72, 0x74, 0x61, 0x6d, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x13, 0x0a, 0x0f,
	0x48, 0x55, 0x4d, 0x41, 0x4e, 0x5f, 0x52, 0x45, 0x53, 0x4f, 0x55, 0x52, 0x43, 0x45, 0x53, 0x10,
	0x00, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x49, 0x4e, 0x41, 0x4e, 0x43, 0x45, 0x53, 0x10, 0x01, 0x12,
	0x17, 0x0a, 0x13, 0x53, 0x41, 0x4c, 0x45, 0x53, 0x5f, 0x41, 0x4e, 0x44, 0x5f, 0x4d, 0x41, 0x52,
	0x4b, 0x45, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x43, 0x55, 0x53, 0x54,
	0x4f, 0x4d, 0x45, 0x52, 0x5f, 0x53, 0x45, 0x52, 0x56, 0x49, 0x43, 0x45, 0x10, 0x03, 0x12, 0x09,
	0x0a, 0x05, 0x4c, 0x45, 0x47, 0x41, 0x4c, 0x10, 0x04, 0x12, 0x0e, 0x0a, 0x0a, 0x50, 0x52, 0x4f,
	0x44, 0x55, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x10, 0x05, 0x12, 0x15, 0x0a, 0x11, 0x51, 0x55, 0x41,
	0x4c, 0x49, 0x54, 0x59, 0x5f, 0x41, 0x53, 0x53, 0x55, 0x52, 0x41, 0x4e, 0x43, 0x45, 0x10, 0x06,
	0x42, 0x34, 0x5a, 0x32, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64,
	0x7a, 0x77, 0x69, 0x65, 0x64, 0x7a, 0x39, 0x30, 0x2f, 0x68, 0x65, 0x6c, 0x70, 0x64, 0x65, 0x73,
	0x6b, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2f, 0x75, 0x73, 0x65, 0x72, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_users_departaments_proto_rawDescOnce sync.Once
	file_services_users_departaments_proto_rawDescData = file_services_users_departaments_proto_rawDesc
)

func file_services_users_departaments_proto_rawDescGZIP() []byte {
	file_services_users_departaments_proto_rawDescOnce.Do(func() {
		file_services_users_departaments_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_users_departaments_proto_rawDescData)
	})
	return file_services_users_departaments_proto_rawDescData
}

var file_services_users_departaments_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_services_users_departaments_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_services_users_departaments_proto_goTypes = []interface{}{
	(DepartamentType)(0), // 0: DepartamentType
	(*Departament)(nil),  // 1: Departament
	(*User)(nil),         // 2: User
}
var file_services_users_departaments_proto_depIdxs = []int32{
	0, // 0: Departament.departament_type:type_name -> DepartamentType
	2, // 1: Departament.users:type_name -> User
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_services_users_departaments_proto_init() }
func file_services_users_departaments_proto_init() {
	if File_services_users_departaments_proto != nil {
		return
	}
	file_services_users_users_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_services_users_departaments_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Departament); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_users_departaments_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_services_users_departaments_proto_goTypes,
		DependencyIndexes: file_services_users_departaments_proto_depIdxs,
		EnumInfos:         file_services_users_departaments_proto_enumTypes,
		MessageInfos:      file_services_users_departaments_proto_msgTypes,
	}.Build()
	File_services_users_departaments_proto = out.File
	file_services_users_departaments_proto_rawDesc = nil
	file_services_users_departaments_proto_goTypes = nil
	file_services_users_departaments_proto_depIdxs = nil
}
